# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Queer and Gender Advancement Alliance of Roorkee
tagline:          'blog'
description:      'Blog of QAGAAR'
url:              http://qagaar-iitr.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           QAGAAR
  url:            

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         github
    url:          https://github.com/qagaar-iitr
    desc:         Fork me on github


menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         QAGAAR
  url:            http://qagaar-iitr.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
